### ISSUE TITLE
Buscar posibles eventos de publicación del artículo.

### ISSUE THREAD

**Issue by hamiltonsalazar** [jmencisom/wikastro#27]
Buscar eventos como congresos, de nivel internacional. Donde la temática a tratar en estos coincida con la tratada en este proyecto para así mismo poder enviar el futuro artículo a elaborar.
Contar con diferentes posibilidades para mostrar a todo el equipo de trabajo y así mismo tomar la decisión de cuál.

**Comment by danielmrno** [comment]
- Opción 1: http://emnlp2018.org
En esta se reciben los artículos hasta el 22 de Mayo 
# Long papers
EMNLP 2018 long paper submissions must describe substantial, original, completed and unpublished work. Wherever appropriate, concrete evaluation and analysis should be included. Each submission will be reviewed by at least three program committee members. Each long paper submission consists of a paper of up to eight (8) pages of content, plus unlimited pages for references; final versions of long papers will be given one additional page (up to nine pages with unlimited pages for references) so that reviewersâ€™ comments can be taken into account.

**Comment by jmencisom** [comment]
Aprobado.

Teniendo en cuenta la fecha límite, por favor plantear plan de trabajo (progrmación dia por día de las actividades requiridas para tener el artículo listo en la fecha establecida).

Gracias.
